services:
  # Web Service (FastAPI)
  - type: web
    name: hwp-api
    env: docker
    dockerfilePath: ./Dockerfile.prod
    repo: https://github.com/Jerome87hyunil/text_parser.git
    branch: main
    region: singapore
    plan: free  # Free tier로 시작
    healthCheckPath: /health
    numInstances: 1
    dockerCommand: python run.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: INFO
      - key: WORKERS
        value: "4"
      - key: MAX_UPLOAD_SIZE
        value: "104857600"
      - key: PROCESS_TIMEOUT
        value: "300"
      - key: ALLOWED_EXTENSIONS
        value: hwp,hwpx,pdf
      - key: CORS_ORIGINS
        value: https://hwp-api.onrender.com,http://localhost:3000
      - key: RATE_LIMIT_ENABLED
        value: "true"
      - key: RATE_LIMIT_DEFAULT
        value: 100/hour
      - key: RATE_LIMIT_EXTRACTION
        value: 20/hour
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      # Database URL - commented out for now since we're not using it yet
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: hwp-api-db
      #     property: connectionString

# Databases section - commented out for initial deployment
# databases:
#   - name: hwp-api-db
#     databaseName: hwp_api
#     user: hwp_api
#     region: singapore
#     plan: free  # Free tier PostgreSQL