# Render Blueprint Configuration
services:
  # Web Service (FastAPI)
  - type: web
    name: hwp-api
    runtime: docker
    dockerfilePath: ./Dockerfile.prod
    repo: https://github.com/Jerome87hyunil/text_parser.git # 실제 GitHub 저장소 URL로 변경
    branch: main
    plan: starter # free, starter, standard, pro 중 선택
    region: singapore # 아시아 지역 (한국 근접)

    # Environment Variables
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: WORKERS
        value: 4
      - key: MAX_UPLOAD_SIZE
        value: 104857600
      - key: PROCESS_TIMEOUT
        value: 300
      - key: ALLOWED_EXTENSIONS
        value: hwp,hwpx,pdf
      - key: CORS_ORIGINS
        value: https://hwp-api.onrender.com,http://localhost:3000
      - key: RATE_LIMIT_ENABLED
        value: true
      - key: RATE_LIMIT_DEFAULT
        value: 100/hour
      - key: RATE_LIMIT_EXTRACTION
        value: 20/hour
      - key: DATABASE_URL
        fromDatabase:
          name: hwp-api-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: hwp-api-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true

    # Health Check
    healthCheckPath: /health

    # Build Configuration
    buildCommand: echo "Build complete"

    # Auto-Deploy on Git Push
    autoDeploy: true

  # PostgreSQL Database
  - type: pserv
    name: hwp-api-db
    databaseName: hwp_api
    user: hwp_api
    plan: starter # free, starter, standard, pro 중 선택
    region: singapore
    ipAllowList: [] # 모든 IP 허용 (필요시 제한)

  # Redis Cache
  - type: redis
    name: hwp-api-redis
    plan: starter # free, starter, standard, pro 중 선택
    region: singapore
    ipAllowList: [] # 모든 IP 허용 (필요시 제한)

  # Background Worker (Celery) - Optional
  - type: worker
    name: hwp-api-worker
    runtime: docker
    dockerfilePath: ./Dockerfile.prod
    repo: https://github.com/Jerome87hyunil/text_parser.git # 실제 GitHub 저장소 URL로 변경
    branch: main
    plan: starter
    region: singapore

    # Worker Start Command
    dockerCommand: celery -A app.core.celery_app worker --loglevel=info --autoscale=4,2

    # Environment Variables (동일한 설정 사용)
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: hwp-api-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: hwp-api-redis
          property: connectionString
      - key: SECRET_KEY
        sync: false # Web service와 동일한 키 사용
      - key: CELERY_AUTOSCALE
        value: true
      - key: CELERY_AUTOSCALE_MAX
        value: 4
      - key: CELERY_AUTOSCALE_MIN
        value: 2
